name: 'Hello'
description: 'Greet someone'
inputs:
  who:
  description: 'The person to greet'
  required: true
  default: 'World'
outputs:
  random-number:
    description: 'random number'
    value: ${{ steps.random-number-generator.outputs.random-number }}
run:
  using: 'composite'
  steps:
    -name: Set Greeting
    run: echo "Hello $INPUT_WHO_TO_GREET."
    shell: true
    env: 
      INPUT_WHO_TO_GREET: ${{ inputs.who }}
    -name: RNG
    - name: Random Number Generator
      id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Run goodbye.sh
      run: goodbye.sh
      shell: bash
