name: CI

env:
  MEME: 67

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_call:
    inputs:
      username:
        description: What is this?
        default: It is a word
        required: false
        type: string

  workflow_dispatch:
    inputs:
      environment:
        description: Choose what to do with this workflow
        required: true
        default: Run the C++ executable
        type: choice
        options:
        - Run the C++ executable
        - Run the Python unittest

jobs:
  reveal-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print it
        run:  |
          echo ${{ secrets.PASSWORD }}
          echo -e 'This is the event: ${{ github.event_name }}'

  do-meme:
    needs: reveal-secret
    runs-on: ubuntu-latest
    steps:
      - name: What is a good number?
        run: | 
          echo "$MEME"
          echo -e 'Username ${{ inputs.username }}'

  github-vars:
    needs: do-meme
    runs-on: ubuntu-latest
    steps:
      - name: Print variables
        run: |
             echo -e 'CI: ' $CI
             echo -e 'GITHUB_ACTION: ' $GITHUB_ACTION
             echo -e 'GITHUB_ACTION_PATH: ' $GITHUB_ACTION_PATH
             echo -e 'GITHUB_ACTION_REPOSITORY: ' $GITHUB_ACTION_REPOSITORY
             echo -e 'GITHUB_ACTIONS: ' $GITHUB_ACTIONS
             echo -e 'GITHUB_ACTOR: ' $GITHUB_ACTOR
             echo -e 'GITHUB_ACTOR_ID: ' $GITHUB_ACTOR_ID
             echo -e 'GITHUB_API_URL'$GITHUB_API_URL


  cpp-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name:  Build C++
        run: |
          g++ main.cpp -o main
          ls -al main
  
  run:
    needs: cpp-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Execute C++ if selected
        if: ${{ inputs.environment == 'Run the C++ executable'}}
        run: ./main
      - name:  Execute Python tests if selected
        if: ${{ inputs.environment == 'Run the Python unittest'}}
        run: python -m unittest -v main.py

  upload:
    runs-on: ubuntu-latest
    needs: cpp-build
    steps:
      - uses: vimtor/action-zip@v1.2
        with:
          files: main.cpp
          dest: artifacts.zip
      - uses: actions/upload-artifact@v4
        with:
          name: Upload executable
          path: ${{ github.workspace }}/artifacts.zip
       

  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run python with command line arguments
        run: python printing.py rm -rf
  
  end-run:
    runs-on: ubuntu-latest
    needs: [github-vars, run]
    steps:
      - name: Goodbye
        run: echo "Goodbye world!"
        
