# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Build code
        run: g++ main.cpp -o main

      # Runs a set of commands using the runners shell
      - name: Run executable
        run: ./main

      - name: Run python unit tests
        run: python -m unittest -v main.py

      - name: List all Github variables
        run: |
             echo -e 'CI: ' $CI
             echo -e 'GITHUB_ACTION: $GITHUB_ACTION'
             echo -e 'GITHUB_ACTION_PATH: $GITHUB_ACTION_PATH'
             echo $GITHUB_ACTION_REPOSITORY
             echo $GITHUB_ACTIONS
             echo $GITHUB_ACTOR
             echo $GITHUB_ACTOR_ID
             echo $GITHUB_API_URL
             echo $GITHUB_BASE_REF
             echo $GITHUB_ENV
             echo $GITHUB_EVENT_NAME
             echo $GITHUB_EVENT_PATH
             echo $GITHUB_GRAPHQL_URL
             echo $GITHUB_HEAD_REF
             echo $GITHUB_JOB
             echo $GITHUB_OUTPUT
             echo $GITHUB_PATH
             echo $GITHUB_REF
             echo $GITHUB_REF_NAME
             echo $GITHUB_REF_PROTECTED
             echo $GITHUB_REF_TYPE
             echo $GITHUB_REPOSITORY
             echo $GITHUB_REPOSITORY_ID
             echo $GITHUB_REPOSITORY_OWNER
             echo $GITHUB_REPOSITORY_OWNER_ID
             echo $GITHUB_RETENTION_DAYS
             echo $GITHUB_RUN_ATTEMPT
             echo $GITHUB_RUN_ID
             echo $GITHUB_RUN_NUMBER
             echo $GITHUB_SERVER_URL
             echo $GITHUB_SHA
             echo $GITHUB_STEP_SUMMARY
             echo $GITHUB_TRIGGERING_ACTOR
             echo $GITHUB_WORKFLOW
             echo $GITHUB_WORKFLOW_REF
             echo $GITHUB_WORKFLOW_SHA
             echo $GITHUB_WORKSPACE
             echo $RUNNER_ARCH
             echo $RUNNER_DEBUG
             echo $RUNNER_ENVIRONMENT
             echo $RUNNER_NAME
             echo $RUNNER_OS
             echo $RUNNER_TEMP
             echo $RUNNER_TOOL_CACHE
